# https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/25482936
# docs - https://cert-manager.io/docs/tutorials/acme/http-validation/#issuing-an-acme-certificate-using-http-validation
# this is what it should look like...
#--#apiVersion: cert-manager.io/v1
#--#kind: Issuer
#--#metadata:
#--#  name: letsencrypt-staging
#--#  namespace: default
#--#spec:
#--#  acme:
#--#    # The ACME server URL
#--#    server: https://acme-staging-v02.api.letsencrypt.org/directory
#--#    # Email address used for ACME registration
#--#    email: user@example.com
#--#    # Name of a secret used to store the ACME account private key
#--#    privateKeySecretRef:
#--#      name: letsencrypt-staging
#--#    # Enable the HTTP-01 challenge provider
#--#    solvers:
#--#    # An empty 'selector' means that this solver matches all domains
#--#    - selector: {}
#--#      http01:
#--#        ingress:
#--#          class: nginx
# this is Stephen's original...          
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{my-email}"                  # req'd by LetsEncrypt
    privateKeySecretRef:
      name: letsencrypt-prod             # not secret containing cert created by cert-manager
    solvers:
      - http01:
          ingress:
            class: nginx
